-- Demo seed for Aanya Sharma persona
-- Use the TypeScript seed script instead (creates auth user + all data):
--
--   npm run seed:aanya
--
-- Requires SUPABASE_SERVICE_ROLE_KEY in .env.local
-- Narrative content: supabase/seed/aanya-narrative.json
